#
# rule: do not use @ to hide commands
#

#generated by ./configure
include autoconf/Makefile.config

OPAMDEPS=yojson menhir ocp-indent ocp-build ppx_tools \
js_of_ocaml-tyxml js_of_ocaml-camlp4 omd lwt

OCPBUILD=ocp-build
OCAMLOPT=ocamlopt.opt
OCAMLC=ocamlc
SRC=src

all:
	if [ ! -d "_obuild" ]; then $(OCPBUILD) init; fi
	$(OCPBUILD)

test:
	$(OCPBUILD) tests

clean:
	$(OCPBUILD) clean

cleanall: distclean

distclean: ocp-distclean

opam-deps:
	opam install $(OPAMDEPS)

install:
	$(OCPBUILD) install         \
		--install-lib $(ocamldir) --install-meta $(metadir)    \
		--install-bin $(bindir)

uninstall:
	$(OCPBUILD) install --uninstall-only

include autoconf/Makefile.rules

