#
# rule: do not use @ to hide commands
#

#generated by ./configure
include autoconf/Makefile.config

OPAMDEPS=yojson menhir ocp-indent ocp-build ppx_tools ppx_deriving

OCPBUILD=ocp-build
OCAMLOPT=ocamlopt.opt
OCAMLC=ocamlc
SRC=src

all:
	if [ ! -d "_obuild" ]; then $(OCPBUILD) init; fi
	$(OCPBUILD)

test:
	$(OCPBUILD) tests

clean:
	$(OCPBUILD) clean

cleanall: distclean

distclean: ocp-distclean

opam-deps:
	opam install $(OPAMDEPS)

install:
	cp _obuild/ocp-lint/ocp-lint.asm $(bindir)/ocp-lint

uninstall:
	rm $(bindir)/ocp-lint

include autoconf/Makefile.rules

