
autoconf/Makefile.config: autoconf/configure
	./configure $(CONFIGURE_ARGS)


# We can override this variable to change the binary to use
# for ocp-build
ifeq ($(OCP_BUILD),)
OCP_BUILD:=ocp-build
endif

_obuild: Makefile
	$(OCP_BUILD) init

ocp-build-build: _obuild
	$(OCP_BUILD)

ocp-build-install: _obuild
	$(OCP_BUILD) install \
		 -install-bin $(bindir) \
		 -install-lib $(ocamldir) \
		 -install-meta $(metadir)

ocp-build-clean: _obuild
	$(OCP_BUILD) clean

ocp-build-distclean:
	rm -rf _obuild

ocp-lint-distclean:
	rm -rf _olint

ocp-autoconf-distclean:
	rm -f autoconf/Makefile.config
	rm -f autoconf/config.ocpgen
	rm -f autoconf/config.ocp2gen
	rm -f autoconf/config.status
	rm -f autoconf/config.log
	rm -f autoconf/ocaml-config.h
	rm -rf autoconf/autom4te.cache/

ocp-distclean: ocp-autoconf-distclean ocp-build-distclean ocp-lint-distclean
