#!/bin/sh

LINT=_obuild/ocp-lint/ocp-lint.asm

$LINT --warn-error tools > /dev/null

if [ "$?" = 0 ]; then
    exit 0
else
    echo "\n/!\\ Please fix the warnings before commiting./!\\"
    exit 1
fi
